### ISSUE TITLE
osd-lyrics无法启动

### ISSUE THREAD

**Issue by GoogleCodeExporter** [memeco/osd-lyrics#306]
```
What steps will reproduce the problem?
请列出导致问题的操作
1.从github下载最新源码并编译
2.终端执行osdlyrics

What's the output in terminal (run with command `osd-lyrics -d debug')?
请给出在终端下运行的输出（使用“osd-lyrics -d
debug”来运行）

*Debug*: in function _client_name_acquired_cb: ol_main.c[633]
Client bus name acquired
*Debug*: in function _name_vanished_cb: ol_main.c[718]
Daemon lost, try to activate it
*Debug*: in function _name_vanished_cb: ol_main.c[731]
Daemon appeared
*Error*: in function _start_daemon_cb: ol_main.c[759]
Unable to start daemon: 
GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process 
/usr/bin/python2 exited with status 1


What's the player and which version you are using?
您使用的播放器是什么？它的版本号是多少？

mpd 0.17.4

What's version of OSD Lyrics?
OSD Lyrics的版本是多少？

OSD Lyrics 0.5.0-git20121117

What's your Linux distro?
您使用哪种发行版？

Archlinux x86_64
```

Original issue reported on code.google.com by `wzy...@gmail.com` on 12 Jul 2013 at 12:39

**Comment by GoogleCodeExporter** [comment]
```
光是编译还是不够的，要安装，而且在arch下运行autogen.sh时要
指定--prefix=/usr

详见 http://code.google.com/p/osd-lyrics/wiki/InstallDaemon
```

Original comment by `tigerso...@gmail.com` on 12 Jul 2013 at 5:35

**Comment by GoogleCodeExporter** [comment]
```
之前表述不清抱歉
我是按照wiki上的做法安装的，并且制定了--prefix=/usr
```

Original comment by `wzy...@gmail.com` on 12 Jul 2013 at 6:25

**Comment by GoogleCodeExporter** [comment]
```
运行osdlyrics-daemon有什么输出么？
```

Original comment by `tigerso...@gmail.com` on 20 Jul 2013 at 5:41

**Comment by GoogleCodeExporter** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/osdlyrics/daemon/main.py", line 24, in <module>
    import lyrics
  File "/usr/local/lib/osdlyrics/daemon/lyrics.py", line 29, in <module>
    import chardet
ImportError: No module named chardet
安装chardet后问题解决。
非常感谢。
```

Original comment by `wzy...@gmail.com` on 25 Jul 2013 at 6:45

**Comment by homtoo** [comment]
在ubuntu 22.04中通过ubuntu software安装，点击程序图标没有启动，在终端输入osdlyrics,提示OSD Lyrics已经运行，程序自动退出。在终端输入osdlyrics-daemon,输出：
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/osdlyrics/daemon/main.py", line 34, in <module>
    import lyrics
  File "/usr/lib/x86_64-linux-gnu/osdlyrics/daemon/lyrics.py", line 43, in <module>
    import lrcdb
  File "/usr/lib/x86_64-linux-gnu/osdlyrics/daemon/lrcdb.py", line 31, in <module>
    import osdlyrics.utils
  File "/usr/lib/python3/dist-packages/osdlyrics/utils.py", line 33, in <module>
    import pycurl
ModuleNotFoundError: No module named 'pycurl'
何解？

**Comment by andloo** [comment]
> 在ubuntu 22.04中通过ubuntu software安装，点击程序图标没有启动，在终端输入osdlyrics,提示OSD Lyrics已经运行，程序自动退出。在终端输入osdlyrics-daemon,输出： Traceback (most recent call last):回溯 (最近一次调用): File "/usr/lib/x86_64-linux-gnu/osdlyrics/daemon/main.py", line 34, in 文件 “/usr/lib/x86_64-linux-gnu/osdlyrics/daemon/main.py”，第34行，在 import lyrics 导入歌词 File "/usr/lib/x86_64-linux-gnu/osdlyrics/daemon/lyrics.py", line 43, in 文件 “/usr/lib/x86_64-linux-gnu/osdlyrics/daemon/lyrics.py”，第43行，在 import lrcdb 导入lrcdb File "/usr/lib/x86_64-linux-gnu/osdlyrics/daemon/lrcdb.py", line 31, in 文件 "/usr/lib/x86_64-linux-gnu/osdlyrics/daemon/lrcdb.py"，第31行，在 import osdlyrics.utils 导入osdlyrics.utils File "/usr/lib/python3/dist-packages/osdlyrics/utils.py", line 33, in 文件 "/usr/lib/python3/dist-packages/osdlyrics/utils.py"，第33行，在 import pycurl 导入pycurl ModuleNotFoundError: No module named 'pycurl'ModuleNotFoundError: 没有名为 “pycurl” 的模块 何解？

我碰到了同样的情况，osdlyrics无法启动，osdlyrics-daemon报错和你的情况相同，我安装了以下包后，问题解决了：
sudo apt update
sudo apt install python3-pycurl

I encountered the same issue where osdlyrics wouldn't start, and osdlyrics-daemon reported the same error. The problem was resolved after I installed the following packages:
sudo apt update
sudo apt install python3-pycurl

**Comment by andloo** [comment]
我碰到了同样的情况，osdlyrics无法启动，osdlyrics-daemon报错和你的情况相同，我安装了以下包后，问题解决了：
sudo apt update
sudo apt install python3-pycurl

I encountered the same issue where osdlyrics wouldn't start, and osdlyrics-daemon reported the same error. The problem was resolved after I installed the following packages:
sudo apt update
sudo apt install python3-pycurl
